"""Update order model for delivery platform

Revision ID: 6189205ffeaf
Revises: ba218055270b
Create Date: 2025-04-11 09:29:52.990209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6189205ffeaf'
down_revision = 'ba218055270b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipper_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('carrier_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('is_assigned', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('pickup_location', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_location', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('orders', sa.Column('delivery_deadline', sa.DateTime(timezone=True), nullable=False))
    op.add_column('orders', sa.Column('package_description', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('dimensions', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=False))
    op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=True)
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['shipper_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['carrier_id'], ['id'])
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'dimensions')
    op.drop_column('orders', 'weight')
    op.drop_column('orders', 'package_description')
    op.drop_column('orders', 'delivery_deadline')
    op.drop_column('orders', 'pickup_date')
    op.drop_column('orders', 'delivery_location')
    op.drop_column('orders', 'pickup_location')
    op.drop_column('orders', 'is_assigned')
    op.drop_column('orders', 'carrier_id')
    op.drop_column('orders', 'shipper_id')
    # ### end Alembic commands ### 